### ISSUE TITLE
master does not build with Clang 4.0.0

### ISSUE THREAD

**Issue by janstary** [litecoin-project/litecoin#342]
Trying to compile master on OpenBSD 6.1  using clang 4.0.0
I am not trying to compile the wallet or the GUI

#### If so, please list the steps to reproduce below:
1. env AUTOMAKE_VERSION=1.15 AUTOCONF_VERSION=2.69 sh autogen.sh 
2. ./configure --prefix=$HOME --mandir=$HOME/man --disable-wallet --without-gui  CC=clang CXX=clang++
3. gmake

The compilation fails on 

 CXX      libbitcoin_server_a-net_processing.o                                                
net_processing.cpp:942:47: error: implicit instantiation of undefined template 'std::__1::array<std::__1::pair<unsigned long long, CNode *>, 2>'                                               
    std::array<std::pair<uint64_t, CNode*>,2> best{{{0, nullptr}, {0, nullptr}}};              
                                              ^                                                
/usr/include/c++/v1/__tuple:198:65: note: template is declared here                            template <class _Tp, size_t _Size> struct _LIBCPP_TYPE_VIS_ONLY array;                         

### What version of litecoin-core are you using?
current git master

### Machine specs:
- OS: OpenBSD
- CPU: Intel Core i5

**Comment by janstary** [comment]
With GCC 4.9.4 as provided by the OpenBSD g++ port it compiles fine.

**Comment by thrasher-** [comment]
Please see here: https://github.com/litecoin-project/litecoin/blob/master/doc/build-openbsd.md

"The default C++ compiler that comes with OpenBSD 5.9 is g++ 4.2. This version is old (from 2007), and is not able to compile the current version of Litecoin Core, primarily as it has no C++11 support"

The latest 4.x g++ version is required and glad to hear it is compiling now.
