### ISSUE TITLE
--with-incompatible-bdb does not work

### ISSUE THREAD

**Issue by janstary** [litecoin-project/litecoin#347]
The current git master requires BDB 4.8 for the wallet.
I am trying to build on OpenBSD 6.1-current which has a BDB 4.6 package.
That's not quite 4.8, but `./confiure` recognizes a `--with-incompatible-bdb` option.
With appropriate `BDB_CFLAGS` and `BDB_LIBS`, the system BDB 4.6.21 gets detected,
but the compilation fails anyway (see below). Apparently some 4.8 features are needed.
I have not tried with 4.7

1. doas pkg_add db4
2. ./configure --prefix=$HOME --mandir=$HOME/man --disable-tests --disable-glibc-back-compat --disable-zmq --enable-wallet --with-incompatible-bdb --with-gui=no   --with-utils  --with-daemon --without-libs --disable-shared --disable-static CC=egcc CXX=eg++ BDB_CFLAGS='-I/usr/local/include/db4/' BDB_LIBS='-L/usr/local/lib/db4/'
3. gmake

```
  CXX      wallet/libbitcoin_wallet_a-db.o     
wallet/db.cpp: In member function 'bool CDBEnv::Open(const boost::filesystem::path&)':         
wallet/db.cpp:97:12: error: 'class DbEnv' has no member named 'log_set_config'                 
     dbenv->log_set_config(DB_LOG_AUTO_REMOVE, 1);                                             
wallet/db.cpp:97:27: error: 'DB_LOG_AUTO_REMOVE' was not declared in this scope                
     dbenv->log_set_config(DB_LOG_AUTO_REMOVE, 1);                                             
wallet/db.cpp: In member function 'void CDBEnv::MakeMock()':                                   
wallet/db.cpp:131:12: error: 'class DbEnv' has no member named 'log_set_config'                
     dbenv->log_set_config(DB_LOG_IN_MEMORY, 1);                                               
wallet/db.cpp:131:27: error: 'DB_LOG_IN_MEMORY' was not declared in this scope                 
     dbenv->log_set_config(DB_LOG_IN_MEMORY, 1);                                               
```
If the `--with-incompatible-bdb` option does not enable a build with BDB other than 4.8 anyway, it should be removed.

Please somebody make a OpenBSD port of BDB 4.8 :-)

**Comment by wrapperband** [comment]
re: If the --with-incompatible-bdb option does not enable a build with BDB other than 4.8 anyway, it should be removed.

It is usually for people who moved on to 5.1, not backwards, so shouldn't be removed.

**Comment by janstary** [comment]
That makes sense; sorry for the confusion.
Perhaps it should be docummented that it means a version _higher_ than 4.8?

**Comment by janstary** [comment]
So, there is no interest in documenting this?
