### ISSUE TITLE
missing header <limits> compile with gcc 11.4

### ISSUE THREAD

**Issue by techy2** [litecoin-project/litecoin#1005]
header dependency issue with gcc 11.4

**Expected behavior**

expected clean build

**Actual behavior**

error: numeric_limit is not a member of std

**To reproduce**

build dependencies using gcc 11.4
qtbase/qmake  -- missing header file

**System information**

litecoin v0.21.4

24 core hp g380

linux with gcc 11.4

Likely caused by gcc 11
Header dependency changes
Some C++ Standard Library headers have been changed to no longer include other headers that they do need to depend on. As such, C++ programs that used standard library components without including the right headers will no longer compile. The following headers are used less widely in libstdc++ and may need to be included explicitly when compiled with GCC 11:
(for std::numeric_limits)

**Comment by techy2** [comment]
FYI depends compiles with gcc 9.4.0 on older system
