### ISSUE TITLE
Failure to build with Boost 1.77

### ISSUE THREAD

**Issue by brad0** [litecoin-project/litecoin#743]
Build testing the OpenBSD ports tree with Boost 1.77. litecoin 0.18.1 fails to build as shown..

```
wallet/test/init_test_fixture.cpp:32:52: error: no member named 'BOOST_FILESYSTEM_C_STR' in 'boost::filesystem::path'
    std::ofstream f(m_walletdir_path_cases["file"].BOOST_FILESYSTEM_C_STR);
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
1 error generated.
```

Being litecoin is a fork of bitcoin this issue has already been fixed there and this commit applies as is.. https://github.com/bitcoin/bitcoin/commit/3a62b8b77e7b1b08c251551e3cf528f94c3392f8

https://github.com/bitcoin/bitcoin/issues/22482

https://github.com/bitcoin/bitcoin/pull/22713

**Comment by qak** [comment]
Since 17 December 2021 it is no longer possible to build the latest stable version of Litecoin (i.e. version 0.18.1) on Arch Linux because of this issue.

**Comment by chappjc** [comment]
Bump.  This really ought to be in 0.21.2

**Comment by njwardhan** [comment]
Integrating changes from the PR: https://github.com/bitcoin/bitcoin/pull/22713 completes the build (over Arch Linux) pretty well.

**Comment by chappjc** [comment]
@DavidBurkett If you are scoping a 0.21.x, please consider cherry-picking https://github.com/bitcoin/bitcoin/pull/22808/commits/d9b18c12903e3ed3b06e1452852159e5b713ff28 so this patch is not required.
The arch linux packages even include this patch so that it can build https://aur.archlinux.org/cgit/aur.git/tree/boost1770.patch?h=litecoin-qt

**Comment by losh11** [comment]
Merged into master branch 24a0299
